// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/applications" | "/dashboard/applications/new" | "/dashboard/company-research" | "/dashboard/mock-interview" | "/dashboard/mock-interview/[sessionId]" | "/dashboard/mock-interview/feedback/[sessionId]" | "/dashboard/profile" | "/dashboard/question-bank" | "/dashboard/question-bank/add" | "/dashboard/resume-optimizer" | "/login" | "/register"
type AppRouteHandlerRoutes = "/api/applications" | "/api/applications/[id]/status" | "/api/applications/stats" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/company/search" | "/api/mock-interview/[sessionId]" | "/api/mock-interview/[sessionId]/answer" | "/api/mock-interview/[sessionId]/feedback" | "/api/mock-interview/create" | "/api/questions" | "/api/research/company" | "/api/resume/optimize" | "/api/scrape/company" | "/api/user/profile"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/applications": {}
  "/api/applications/[id]/status": { "id": string; }
  "/api/applications/stats": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/company/search": {}
  "/api/mock-interview/[sessionId]": { "sessionId": string; }
  "/api/mock-interview/[sessionId]/answer": { "sessionId": string; }
  "/api/mock-interview/[sessionId]/feedback": { "sessionId": string; }
  "/api/mock-interview/create": {}
  "/api/questions": {}
  "/api/research/company": {}
  "/api/resume/optimize": {}
  "/api/scrape/company": {}
  "/api/user/profile": {}
  "/dashboard": {}
  "/dashboard/applications": {}
  "/dashboard/applications/new": {}
  "/dashboard/company-research": {}
  "/dashboard/mock-interview": {}
  "/dashboard/mock-interview/[sessionId]": { "sessionId": string; }
  "/dashboard/mock-interview/feedback/[sessionId]": { "sessionId": string; }
  "/dashboard/profile": {}
  "/dashboard/question-bank": {}
  "/dashboard/question-bank/add": {}
  "/dashboard/resume-optimizer": {}
  "/login": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
