// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications/new">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/company-research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/company-research">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/company-research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/mock-interview/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mock-interview/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/mock-interview/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/mock-interview/feedback/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mock-interview/feedback/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/mock-interview/feedback/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/mock-interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mock-interview">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/mock-interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/question-bank/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/question-bank/add">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/question-bank/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/question-bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/question-bank">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/question-bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/resume-optimizer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/resume-optimizer">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/resume-optimizer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/applications/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/applications/[id]/status">> = Specific
  const handler = {} as typeof import("../../../app/api/applications/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/applications">> = Specific
  const handler = {} as typeof import("../../../app/api/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/applications/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/applications/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/applications/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/company/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company/search">> = Specific
  const handler = {} as typeof import("../../../app/api/company/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock-interview/[sessionId]/answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock-interview/[sessionId]/answer">> = Specific
  const handler = {} as typeof import("../../../app/api/mock-interview/[sessionId]/answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock-interview/[sessionId]/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock-interview/[sessionId]/feedback">> = Specific
  const handler = {} as typeof import("../../../app/api/mock-interview/[sessionId]/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock-interview/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock-interview/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../app/api/mock-interview/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock-interview/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock-interview/create">> = Specific
  const handler = {} as typeof import("../../../app/api/mock-interview/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/questions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions">> = Specific
  const handler = {} as typeof import("../../../app/api/questions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/research/company/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/company">> = Specific
  const handler = {} as typeof import("../../../app/api/research/company/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/resume/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resume/optimize">> = Specific
  const handler = {} as typeof import("../../../app/api/resume/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/scrape/company/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scrape/company">> = Specific
  const handler = {} as typeof import("../../../app/api/scrape/company/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
